version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 13
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install -g yarn
      - yarn
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
      - bash -c 'if [ "$CODEBUILD_BUILD_SUCCEEDING" == "0" ]; then exit 1; fi'
      
      - aws s3 sync build ${S3_BUCKET}
        --delete 
        --exclude "*.js"
        
      - aws s3 sync build ${S3_BUCKET} 
        --exclude "*" 
        --include "*.js" 
        --content-type="text/javascript;charset=utf-8" 
        --delete
      
      - aws cloudfront create-invalidation 
        --distribution-id ${CLOUDFRONT_DISTRIBUTION} 
        --paths /index.html 
cache:
  paths:
    - 'node_modules/**/*'